name: QAD
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.3.7
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - contourpy=1.0.5
  - cycler=0.11.0
  - ffmpeg=4.3.2
  - fonttools=4.51.0
  - freetype=2.10.4
  - gmp=6.2.1
  - gnutls=3.6.13
  - importlib_resources=6.4.0
  - intel-openmp=2023.1.0
  - jpeg=9f
  - kiwisolver=1.4.4
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - matplotlib-base=3.7.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - nettle=3.6
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.18
  - packaging=24.1
  - pandas=2.0.3
  - pillow=10.4.0
  - pip=24.2
  - pyparsing=3.0.9
  - python=3.8.20
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - pytz=2024.1
  - readline=8.2
  - seaborn=0.13.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - unicodedata2=15.1.0
  - wheel=0.44.0
  - x264=1!161.3030
  - xz=5.6.4
  - zipp=3.20.2
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.2.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - appdirs==1.4.4
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - backcall==0.2.0
      - black==19.10b0
      - brotli==1.1.0
      - cachetools==5.5.2
      - certifi==2025.1.31
      - cfgv==3.4.0
      - charset-normalizer==3.4.1
      - click==8.1.8
      - codecarbon==2.1.4
      - colorama==0.4.6
      - desed==1.3.8
      - distlib==0.3.9
      - dnspython==2.6.1
      - docopt-ng==0.9.0
      - eval-type-backport==0.2.2
      - executing==2.2.0
      - filelock==3.16.1
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - fuzzywuzzy==0.18.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==2.38.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - h5py==3.11.0
      - hf-xet==1.1.5
      - huggingface-hub==0.34.2
      - identify==2.6.1
      - idna==3.10
      - ipython==8.12.3
      - jams==0.3.4
      - jedi==0.19.2
      - jinja2==3.1.6
      - jsonpickle==4.0.5
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - lightning-utilities==0.11.9
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib-inline==0.1.7
      - mir-eval==0.8.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - munch==4.0.0
      - mutagen==1.47.0
      - networkx==3.1
      - nodeenv==1.9.1
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - onnx==1.17.0
      - opencv-python==4.12.0.88
      - parso==0.8.4
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pkgutil-resolve-name==1.3.10
      - pre-commit==3.5.0
      - prompt-toolkit==3.0.51
      - propcache==0.2.0
      - protobuf==5.29.4
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycodestyle==2.5.0
      - pycryptodomex==3.22.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pygments==2.19.1
      - pyloudnorm==0.1.1
      - pymongo==4.10.1
      - pynvml==11.5.3
      - pytorch-lightning==1.9.5
      - pyyaml==6.0.2
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - resampy==0.4.3
      - rpds-py==0.20.1
      - rsa==4.9
      - sacred==0.8.7
      - scaper==1.6.5
      - sentry-sdk==2.40.0
      - six==1.17.0
      - smmap==5.0.2
      - sortedcontainers==2.4.0
      - sox==1.4.0
      - soxbindings==1.2.3
      - stack-data==0.6.3
      - sympy==1.13.3
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - thop==0.1.1-2209072238
      - timm==0.4.5
      - toml==0.10.2
      - torch==2.4.1+cu118
      - torchaudio==2.4.1+cu118
      - torchlibrosa==0.1.0
      - torchmetrics==1.5.2
      - torchvision==0.19.1+cu118
      - traitlets==5.14.3
      - triton==3.0.0
      - typed-ast==1.5.5
      - types-python-dateutil==2.9.0.20241206
      - ultralytics==8.3.179
      - ultralytics-thop==2.0.14
      - urllib3==2.2.3
      - virtualenv==20.31.1
      - wandb==0.22.1
      - wcwidth==0.2.13
      - websockets==13.1
      - werkzeug==3.0.6
      - wget==3.2
      - wrapt==1.17.2
      - yarl==1.15.2
      - yt-dlp==2024.10.22
